"""
Legal Assistance & Access Engine — LegalLens AI.
Directly implements the core mission of PromptWars 2026:
"AI for Legal Assistance & Access" — Democratizing access to justice for freelancers,
tenants, non-native speakers, and small business owners.

Key Capabilities:
- Multilingual Legal Translation (Hindi, Spanish, French, German, Telugu, Tamil, Bengali, Portuguese)
- Localized plain-language glossaries of tricky legal concepts
- Instant Pre-Loaded Sample Contracts library (zero-barrier evaluation)
- Exportable comprehensive Legal Health & Audit Reports (Markdown/PDF)
"""

import logging
from typing import Dict, Any, List, Optional
import groq_service
from sample_contracts import SAMPLE_CONTRACTS

logger = logging.getLogger("LegalAccessEngine")


class LegalAccessEngine:
    """
    Engine dedicated to broadening access to legal knowledge and democratizing contract literacy.
    """

    def __init__(self, default_api_key: Optional[str] = None):
        self.default_api_key = default_api_key

    def translate_to_regional_language(
        self, 
        text: str, 
        target_language: str = "Hindi", 
        user_api_key: Optional[str] = None
    ) -> Dict[str, Any]:
        """
        Translates complex legal clauses into regional languages with plain explanations.

        Args:
            text: Legal text or executive summary to translate.
            target_language: Target language (e.g., 'Hindi', 'Spanish', 'French').
            user_api_key: Optional client-provided Groq API key.

        Returns:
            Dictionary containing target_language, translated_title, translated_content,
            plain_explanation_target_lang, and key_terms_glossary list.
        """
        api_key = user_api_key or self.default_api_key
        logger.info(f"Translating legal document to {target_language}...")
        return groq_service.translate_legal_text(text, target_language=target_language, user_api_key=api_key)

    def get_sample_contracts(self) -> List[Dict[str, Any]]:
        """Returns the pre-loaded legal contracts catalog for instant demonstration."""
        return [
            {
                "id": v["id"],
                "title": v["title"],
                "category": v["category"],
                "parties": v["parties"],
                "summary": v["summary"],
                "text": v["text"]
            }
            for v in SAMPLE_CONTRACTS.values()
        ]

    def generate_legal_audit_report(self, title: str, parties: str, analysis: Dict[str, Any]) -> str:
        """Generates a comprehensive formatted Markdown legal audit report ready for counsel or export."""
        score = analysis.get("overall_health_score", "N/A")
        tier = analysis.get("risk_tier", "N/A")
        exec_sum = analysis.get("executive_summary", "N/A")
        layman = analysis.get("layman_eli5", "N/A")
        metrics = analysis.get("key_metrics", {})
        red_flags = analysis.get("red_flags", [])
        checklist = analysis.get("action_checklist", [])

        report_lines = [
            "# LEGALLENS AI — COMPREHENSIVE LEGAL AUDIT REPORT",
            "Built for PromptWars 2026 (AI for Legal Assistance & Access)",
            "",
            f"**DOCUMENT:** {title}",
            f"**PARTIES:** {parties}",
            f"**LEGAL SAFETY SCORE:** {score} / 100 ({tier})",
            "",
            "## 1. EXECUTIVE COMMERCIAL BRIEFING",
            exec_sum,
            "",
            "## 2. PLAIN-ENGLISH (LAYMAN / ELI5) EXPLANATION",
            layman,
            "",
            "## 3. CORE COMMERCIAL TERMS & LIABILITIES",
            f"- Financial Exposure: {metrics.get('total_financial_exposure', 'N/A')}",
            f"- Payment Terms: {metrics.get('payment_terms', 'N/A')}",
            f"- Termination Notice: {metrics.get('termination_notice', 'N/A')}",
            f"- Governing Law & Forum: {metrics.get('governing_jurisdiction', 'N/A')}",
            "",
            "## 4. RED-FLAG VULNERABILITY RADAR"
        ]

        for i, rf in enumerate(red_flags, 1):
            report_lines.extend([
                f"### [{rf.get('id', f'RF-{i}')}] {rf.get('clause_reference', 'Clause')} (Severity: {rf.get('severity', 'High')})",
                f"- **Category:** {rf.get('category', 'Risk')}",
                f"- **Problem:** {rf.get('problem', 'N/A')}",
                f"- **Real-World Consequence:** {rf.get('real_world_consequence', 'N/A')}",
                f"- **Recommended Remedy:** {rf.get('recommended_remedy', 'N/A')}",
                ""
            ])

        report_lines.extend([
            "## 5. PRE-SIGNING ACTION CHECKLIST"
        ])
        for item in checklist:
            report_lines.append(f"- [ ] {item}")

        report_lines.extend([
            "",
            "---",
            "**DISCLAIMER:** This report was generated by LegalLens AI for informational guidance and does not substitute for licensed legal representation."
        ])

        return "\n".join(report_lines)


# Global default instance
legal_access_engine = LegalAccessEngine()
